package gui.contactos;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import utilerias.Colores;
import utilerias.LongitudesAtributosBD;
import utilerias.OperacionesBaseDatos;


public class AgregarContacto extends javax.swing.JFrame {

    private static AgregarContacto instancia = null;
    private Municipio municipios[];
    private Estado estados[];
    private Genero[] generos;
    private String rutaFoto;
    public static DefaultListModel modeloListaTelefonos = new DefaultListModel();
    public static DefaultListModel modeloListaCorreosElectronicos = new DefaultListModel();
    public static DefaultComboBoxModel modeloComboBoxMunicipios = new DefaultComboBoxModel();
    public static DefaultComboBoxModel modeloComboBoxEstados = new DefaultComboBoxModel();
    public static DefaultComboBoxModel modeloComboBoxGeneros = new DefaultComboBoxModel();
    
    public AgregarContacto() {
        initComponents();
        OperacionesBaseDatos.levantarServidorXampp();
        this.setTitle("AgendITA: Agegar contacto");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src//img//agregar_usuario_128.png"));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarDatosIniciales();
        jListCorreosElectronicos.setToolTipText("Los correos electronicos tendran a lo mucho " + LongitudesAtributosBD.LONGITUD_EMAIL + "caracteres");
        jComboBoxMunicipio.setMaximumRowCount(10);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldApellidoMaterno = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldApellidoPaterno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldColonia = new javax.swing.JTextField();
        jTextFieldCalle = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jComboBoxMunicipio = new javax.swing.JComboBox<>();
        jButtonAgregarCiudad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabelImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCorreosElectronicos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTelefonos = new javax.swing.JList<>();
        jButtonGenero = new javax.swing.JButton();
        jButtonAgregarFoto = new javax.swing.JButton();
        jButtonTelefono = new javax.swing.JButton();
        jButtonCorreoElectronico = new javax.swing.JButton();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 220, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true), "Nombre del contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jTextFieldApellidoMaterno.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Apellido Materno"));
        jTextFieldApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoMaternoFocusLost(evt);
            }
        });
        jTextFieldApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoMaternoKeyTyped(evt);
            }
        });

        jTextFieldNombres.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Nombre(s)"));
        jTextFieldNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombresFocusLost(evt);
            }
        });
        jTextFieldNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombresKeyTyped(evt);
            }
        });

        jTextFieldApellidoPaterno.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Apellido Paterno"));
        jTextFieldApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoPaternoFocusLost(evt);
            }
        });
        jTextFieldApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoPaternoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jTextFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(220, 220, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), "Direccion del contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jTextFieldColonia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Colonia"));
        jTextFieldColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldColoniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldColoniaFocusLost(evt);
            }
        });
        jTextFieldColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldColoniaKeyTyped(evt);
            }
        });

        jTextFieldCalle.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Calle"));
        jTextFieldCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCalleFocusLost(evt);
            }
        });
        jTextFieldCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCalleKeyTyped(evt);
            }
        });

        jTextFieldNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Número"));
        jTextFieldNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroFocusLost(evt);
            }
        });
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        jComboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMunicipio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Municipio(Estado)"));

        jButtonAgregarCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/anadir-lugar_64.png"))); // NOI18N
        jButtonAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextFieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonAgregarCiudad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregarCiudad)))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(220, 255, 220));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Datos misceláneos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Género"));

        jLabelImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Foto"));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono_24.png"))); // NOI18N
        jLabel2.setText("Teléfonos");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/emails_24.png"))); // NOI18N
        jLabel3.setText("Correos electrónicos");

        jListCorreosElectronicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListCorreosElectronicos);

        jListTelefonos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListTelefonos);

        jButtonGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_genero_32.png"))); // NOI18N
        jButtonGenero.setMaximumSize(new java.awt.Dimension(32, 32));
        jButtonGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneroActionPerformed(evt);
            }
        });

        jButtonAgregarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_foto_2_32.png"))); // NOI18N
        jButtonAgregarFoto.setPreferredSize(new java.awt.Dimension(32, 32));
        jButtonAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFotoActionPerformed(evt);
            }
        });

        jButtonTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_telefono_32.png"))); // NOI18N
        jButtonTelefono.setPreferredSize(new java.awt.Dimension(32, 32));
        jButtonTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelefonoActionPerformed(evt);
            }
        });

        jButtonCorreoElectronico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_correo_32.png"))); // NOI18N
        jButtonCorreoElectronico.setPreferredSize(new java.awt.Dimension(32, 32));
        jButtonCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorreoElectronicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCorreoElectronico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButtonAgregarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(157, 157, 157))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgregarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar_16.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_16.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jButtonAceptar)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonCancelar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static AgregarContacto getInstancia(){
        synchronized (AgregarContacto.class) {
            if (instancia == null) {
                instancia = new AgregarContacto();
            }
        }
        return instancia;
    } 
            
        private int buscarPosMunicipio (String municipio){
            for (int i = 0; i < municipios.length; i++) {
                return i;
            }
        return -1;
        }    
        
        public void recargarMunicipios(String municipio, int idEstado){
            Object [][] datos = OperacionesBaseDatos.buscarMunicipio(municipio, idEstado);
            
            if(datos != null){
                Municipio mun = new Municipio();
                mun.setId(Integer.parseInt(String.valueOf(datos[0][0])));
                mun.setNombre(String.valueOf(datos[0][1]));
                mun.setIdEstado(Integer.parseInt(String.valueOf(datos[0][2])));
                
                modeloComboBoxMunicipios.insertElementAt(mun, 0);
                modeloComboBoxMunicipios.setSelectedItem(mun);
                
                //actualizar el vector municipios
                datos = OperacionesBaseDatos.buscarMunicipios();
                this.municipios = new Municipio[datos.length];
                for (int i = 0; i < municipios.length; i++) {
                    municipios[i] = new Municipio();
                    municipios[i].setId(Integer.parseInt(String.valueOf(datos[i][0])));
                    municipios[i].setNombre(String.valueOf(datos[i][1]));
                    municipios[i].setIdEstado(Integer.parseInt(String.valueOf(datos[0][2])));
                    municipios[i].setNombreEstado(String.valueOf(datos[0][3]));
                }
            }
        }
        
        private void cargarMunicipios(){
            Object [][] datos = OperacionesBaseDatos.buscarMunicipios();
            this.municipios = new Municipio[datos.length];
            for (int i = 0; i < municipios.length; i++) {
                municipios[i] = new Municipio();
                    municipios[i].setId(Integer.parseInt(String.valueOf(datos[i][0])));
                    municipios[i].setNombre(String.valueOf(datos[i][1]));
                    municipios[i].setIdEstado(Integer.parseInt(String.valueOf(datos[0][2])));
                    municipios[i].setNombreEstado(String.valueOf(datos[0][3]));
            }
            modeloComboBoxMunicipios = new DefaultComboBoxModel(municipios);
            jComboBoxMunicipio.setModel(modeloComboBoxMunicipios);
        }
        
        private void cargarGeneros(){
            Object [][] datos = OperacionesBaseDatos.buscarGeneros();
            this.generos = new Genero [datos.length];
            for (int i = 0; i < generos.length; i++) {
                generos[i]= new Genero();
                generos[i].setId(Integer.parseInt(String.valueOf(datos[i][0])));
                generos[i].setGenero(String.valueOf(datos[i][1]));
            }
        modeloComboBoxGeneros = new DefaultComboBoxModel(generos);
        jComboBoxGenero.setModel(modeloComboBoxGeneros);
        
        }
        
        public void recargarGeneros(String genero){
            Object [][] datos = OperacionesBaseDatos.buscarGenero(genero);
            
            if(datos != null){
                Genero gen = new Genero();
                gen.setId(Integer.parseInt(String.valueOf(datos[0][0])));
                gen.setGenero(String.valueOf(datos[0][1]));
                modeloComboBoxGeneros.insertElementAt(gen, 0);
                modeloComboBoxGeneros.setSelectedItem(gen);
            }
            //actualizar el vector generos
        
        datos = OperacionesBaseDatos.buscarGeneros();
        this.generos = new Genero [datos.length];
            for (int i = 0; i < generos.length; i++) {
                generos[i] = new Genero();
                generos[i].setId(Integer.parseInt(String.valueOf(datos[i][0])));
                generos[i].setGenero(String.valueOf(datos[i][1]));
            }
        }
        
        public void cargarEstados(){
            Object [][] datos = OperacionesBaseDatos.buscarEstados();
            this.estados = new Estado[datos.length];
            for (int i = 0; i < estados.length; i++) {
                estados[i] = new Estado();
                estados[i].setId(Integer.parseInt(String.valueOf(datos[i][0])));
                estados[i].setNombre(String.valueOf(datos[i][1]));
            }
        }
        public void cargarDatosIniciales(){
            cargarMunicipios();
            cargarEstados();
            cargarGeneros();
        }
        
        private int buscarIdGenero(String genero){
            for (int i = 0; i < generos.length; i++) {
                if (generos[i].getGenero().equals(genero)) {
                    return generos[i].getId();
                }
            }
            return -1;
        }
        
        private int buscarIdMunicipio(String municipio){
            for (int i = 0; i < municipios.length; i++) {
                if(municipios[i].getNombre().equals(municipio)){
                return municipios[i].getId();
                }
                
            }
        return -1;
        }
        
        private int buscarIdEstado(String estado){
            for (int i = 0; i < estados.length; i++) {
                if (estados[i].getNombre().equals(estado)) {
                    return estados[i].getId();
                }
            }
            return -1;
        }
        
        private void limpiarFormulario(){
            jTextFieldNombres.setText("");
            jTextFieldApellidoPaterno.setText("");
            jTextFieldApellidoMaterno.setText("");
            jTextFieldCalle.setText("");
            jTextFieldNumero.setText("");
            jTextFieldColonia.setText("");
            jComboBoxMunicipio.setSelectedIndex(0);
            jComboBoxGenero.setSelectedIndex(0);
            jDateChooserFechaNacimiento.setDate(null);
            jLabelImagen.setIcon(null);
            modeloListaTelefonos.clear();
            modeloListaCorreosElectronicos.clear();
        
        }
        
        
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        //verificamos que todos los datos hayan sido capturados en el formulario
        if(jTextFieldNombres.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "El nombre del contacto es obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jTextFieldNombres.requestFocus();
        }else if (jTextFieldApellidoPaterno.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "El apellido paterno del contacto es obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jTextFieldApellidoPaterno.requestFocus();
    }//GEN-LAST:event_jButtonAceptarActionPerformed
     else if (jTextFieldApellidoMaterno.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "El apellido materno del contacto es obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jTextFieldApellidoMaterno.requestFocus(); 
    }else if (jTextFieldCalle.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "El calle es un dato obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jTextFieldCalle.requestFocus();
    }else if (jTextFieldNumero.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "El numero de casa es un dato obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jTextFieldNumero.requestFocus();
    
    }else if (jTextFieldColonia.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "El colonia es un dato obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jTextFieldColonia.requestFocus();
    }else if (jDateChooserFechaNacimiento.getDate().equals("")){
            JOptionPane.showConfirmDialog(null, "La fecha de nacimiento es un dato obligatorio",
                    "AgendITA: Agregar contacto", JOptionPane.ERROR_MESSAGE);
                    jDateChooserFechaNacimiento.requestFocusInWindow();
    }else{
        //Agregamos los datos a la tabla contactos
        String nombres = jTextFieldNombres.getText();
        String ape_paterno = jTextFieldApellidoPaterno.getText();
        String ape_materno = jTextFieldApellidoMaterno.getText();
        
        String fecha_nac = "1999-12-31";
        
            if (jDateChooserFechaNacimiento.getDate() != null) {
                SimpleDateFormat dcn = new SimpleDateFormat ("yyyy-MM-dd");
                fecha_nac = dcn.format(jDateChooserFechaNacimiento.getDate());
            }
            
            int idGenero = buscarIdGenero(String.valueOf(jComboBoxGenero.getSelectedItem()));
            
            String calle = jTextFieldCalle.getText();
            int numero = 0;
            if(!jTextFieldNumero.getText().equals("")){
                numero = Integer.parseInt(jTextFieldNumero.getText());
            }
            
            String colonia = jTextFieldColonia.getText();
            
            Municipio municipio = (Municipio) jComboBoxMunicipio.getSelectedItem();
            int idMunicipio = municipio.getId();
            int idEstado = municipio.getIdEstado();
            
            int resultado1 = OperacionesBaseDatos.insertarContacto(nombres, ape_paterno, ape_materno,
                fecha_nac,idGenero, rutaFoto, calle, numero, colonia, idMunicipio, idEstado);
            int resultado2 = 0;
            int resultado3 = 0;
            
            //posteriormente agregamos los numeros telefonicos y los correos elecronicos
            
            int idContacto = OperacionesBaseDatos.ultimoRegistroInsertado();
        if(modeloListaTelefonos.size() > 0){
            
                //si hay al menos un telefono en la lista de telefonos
                for (int i = 0; i < modeloListaTelefonos.size(); i++) {
                    String telefono = String.valueOf(modeloListaTelefonos.getElementAt(i));
                    resultado2 = OperacionesBaseDatos.insertarTelefono(idContacto, telefono);     
            }
        }
            if (modeloListaCorreosElectronicos.size() > 0) {
                for (int i = 0; i < modeloListaCorreosElectronicos.size(); i++) {
                    String correo = String.valueOf(modeloListaTelefonos);
                    resultado3 = OperacionesBaseDatos.insertarCorreoElectronico(idContacto, correo);
                    
                }
            }
            
            if(resultado1 != -1 && resultado2 != -1 && resultado3 != -1)
            JOptionPane.showMessageDialog(null, "Registro insertado con exito", 
                    "AgendITA: Agregar contacto", JOptionPane.INFORMATION_MESSAGE);
    }
        
        //salimos del formulario de altas de contactos
        limpiarFormulario();
        this.setVisible(false);
        GestionContactos gestionContactos = GestionContactos.getInstancia();
        gestionContactos.setVisible(true);
   
    }
                        
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            limpiarFormulario();
            GestionContactos contactos = GestionContactos.getInstancia();
            contactos.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombresFocusGained
        jTextFieldNombres.setBackground(Colores.COLOR_FOCO);
        jTextFieldNombres.selectAll();
    }//GEN-LAST:event_jTextFieldNombresFocusGained

    private void jTextFieldNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombresFocusLost
        jTextFieldNombres.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldNombresFocusLost

    private void jTextFieldNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombresKeyTyped
        char c = evt.getKeyChar();
        String texto = jTextFieldNombres.getText();
        if((texto.length() + 1 > LongitudesAtributosBD.LONGITUD_NOMBRES_CONTACTO) 
                || (c >= '0' && c <= '9')){
            evt.consume();
        }    
    }//GEN-LAST:event_jTextFieldNombresKeyTyped

    private void jTextFieldApellidoPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoPaternoFocusGained
         jTextFieldApellidoPaterno.setBackground(Colores.COLOR_FOCO);
        jTextFieldApellidoPaterno.selectAll();
    }//GEN-LAST:event_jTextFieldApellidoPaternoFocusGained

    private void jTextFieldApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoPaternoFocusLost
        jTextFieldApellidoPaterno.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldApellidoPaternoFocusLost

    private void jTextFieldApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoPaternoKeyTyped
        char c = evt.getKeyChar();
        String texto = jTextFieldApellidoPaterno.getText();
        if((texto.length() + 1 > LongitudesAtributosBD.LONGITUD_APELLIDO_PATERNO_CONTACTO) 
                || (c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldApellidoPaternoKeyTyped

    private void jTextFieldApellidoMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMaternoFocusGained
        jTextFieldApellidoMaterno.setBackground(Colores.COLOR_FOCO);
        jTextFieldApellidoMaterno.selectAll();
    }//GEN-LAST:event_jTextFieldApellidoMaternoFocusGained

    private void jTextFieldApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMaternoFocusLost
     jTextFieldApellidoMaterno.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldApellidoMaternoFocusLost

    private void jTextFieldApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMaternoKeyTyped
       char c = evt.getKeyChar();
        String texto = jTextFieldApellidoMaterno.getText();
        if((texto.length() + 1 > LongitudesAtributosBD.LONGITUD_APELLIDO_MATERNO_CONTACTO) 
                || (c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldApellidoMaternoKeyTyped

    private void jTextFieldCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCalleFocusGained
        jTextFieldCalle.setBackground(Colores.COLOR_FOCO);
        jTextFieldCalle.selectAll();
    }//GEN-LAST:event_jTextFieldCalleFocusGained

    private void jTextFieldCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCalleFocusLost
        jTextFieldCalle.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldCalleFocusLost

    private void jTextFieldCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCalleKeyTyped
        char c = evt.getKeyChar();
        String texto = jTextFieldCalle.getText();
        if((texto.length() + 1 > LongitudesAtributosBD.LONGITUD_CALLE_CONTACTO) 
                || (c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCalleKeyTyped

    private void jTextFieldNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFocusGained

        jTextFieldNumero.setBackground(Colores.COLOR_FOCO);
        jTextFieldNumero.selectAll();
    }//GEN-LAST:event_jTextFieldNumeroFocusGained

    private void jTextFieldNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFocusLost
      
        jTextFieldNumero.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldNumeroFocusLost

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped

        char c = evt.getKeyChar();
        String texto = jTextFieldNumero.getText();
        if((texto.length() + 1 > LongitudesAtributosBD.LONGITUD_NUMERO_CONTACTO) 
                || (c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldColoniaFocusGained
        jTextFieldColonia.setBackground(Colores.COLOR_FOCO);
        jTextFieldColonia.selectAll();
    }//GEN-LAST:event_jTextFieldColoniaFocusGained

    private void jTextFieldColoniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldColoniaFocusLost
 
        jTextFieldColonia.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldColoniaFocusLost

    private void jTextFieldColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldColoniaKeyTyped
        
        char c = evt.getKeyChar();
        String texto = jTextFieldColonia.getText();
        if((texto.length() + 1 > LongitudesAtributosBD.LONGITUD_COLONIA_CONTACTO) 
                || (c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldColoniaKeyTyped

    private void jButtonAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCiudadActionPerformed
        
        AgregarCiudad agregarCiudad = AgregarCiudad.getInstancia(this, true);
        agregarCiudad.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarCiudadActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFotoActionPerformed
        
        JFileChooser fc = new JFileChooser();
        File workingDirectory = new File(System.getProperty("user.dir"));
        fc.setCurrentDirectory(workingDirectory);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "PNG","JPG");
        fc.setFileFilter(filtro);
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int respuesta = fc.showOpenDialog(this);
        
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            try{
                File archivo = fc.getSelectedFile();
                copiarFoto(archivo);
                BufferedImage img = ImageIO.read(archivo);
                int alto = img.getHeight();
                int ancho = img.getWidth();
                int nuevoAlto = 0;
                int nuevoAncho = 0;
                if (alto > ancho) {
                    nuevoAlto = 235;
                    nuevoAncho = ancho * 235 / alto;
                }else if (ancho > alto) {
                    nuevoAlto = alto * 235 / ancho;
                    nuevoAncho = 235;
                }else{
                    nuevoAlto = 235;
                    nuevoAncho = 235;
                }
                Image nuevaImg = img.getScaledInstance(nuevoAncho, nuevoAlto,
                        java.awt.Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(nuevaImg);
                mostrarImagen(imageIcon);
            } catch (IOException ex) {
                Logger.getLogger(AgregarContacto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    
    }//GEN-LAST:event_jButtonAgregarFotoActionPerformed

    private void jButtonTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelefonoActionPerformed
        //agregar numero telefonico
        AgregarTelefonoContacto nuevoTelefono = AgregarTelefonoContacto.getInstancia(this,true);
        nuevoTelefono.setVisible(true);
    }//GEN-LAST:event_jButtonTelefonoActionPerformed

    private void jButtonCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorreoElectronicoActionPerformed
        AgregarCorreoContacto nuevoCorreo = AgregarCorreoContacto.getInstancia(this, true);
        nuevoCorreo.setVisible(true);
    }//GEN-LAST:event_jButtonCorreoElectronicoActionPerformed

    private void jButtonGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeneroActionPerformed
        AgregarGenero agregarGenero = AgregarGenero.getInstancia(this, true);
        agregarGenero.setVisible(true);
    }//GEN-LAST:event_jButtonGeneroActionPerformed


    private String buscarEstado(String municipio){
        for (Municipio municipio1 : municipios) {
            if(municipio.equals(municipio1.getNombre())){
                return municipio1.getNombreEstado();//id del municipio en la bd
            }
        }
    return "";
    }
    
    private void copiarFoto(File archivo){
        try{
            rutaFoto = "src//fotos//" + archivo.getName();
            Path destino = Paths.get(rutaFoto);
            Path origen = Paths.get(archivo.getPath());
            Files.copy(origen, destino, REPLACE_EXISTING);
        
        } catch (IOException ex) {
            Logger.getLogger(AgregarContacto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private String buscarPrimerMunicipio(String estado){
        for (int i = 0; i < municipios.length; i++) {
            if(municipios[i].getNombreEstado().equals(estado)){
                return municipios[i].getNombre();
            }
        }
    return null;
    }
    
    private void mostrarImagen(ImageIcon icono){
        for (int i = 0; i < 2; i++) {
            icono.getImage().flush();
            jLabelImagen.setIcon(icono);
            jLabelImagen.setHorizontalAlignment(JLabel.CENTER);
            
        }
    }
    
    private void cerrar(){
        this.dispose();
        GestionContactos usuarios = GestionContactos.getInstancia();
        usuarios.setVisible(true);
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAgregarCiudad;
    private javax.swing.JButton jButtonAgregarFoto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCorreoElectronico;
    private javax.swing.JButton jButtonGenero;
    private javax.swing.JButton jButtonTelefono;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxMunicipio;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JList<String> jListCorreosElectronicos;
    private javax.swing.JList<String> jListTelefonos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldApellidoMaterno;
    private javax.swing.JTextField jTextFieldApellidoPaterno;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldColonia;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
